alias ls="ls --color=auto -h --group-directories-first"
alias rr="rm -r"
alias gca="git commit -a"
alias gsm="git push origin main"
alias glm="git pull origin main"
alias hibernate="systemctl hibernate"
